import { StyleSheet, Dimensions } from "react-native";

const { height, width } = Dimensions.get("window");
const mapH = height * 0.75; // Carte plus grande

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#fff" },
  mapContainer: { width: "100%", height: mapH, position: "relative" },
  map: { width: "100%", height: "100%" },
  optionsButton: {
    position: "absolute",
    top: 40, // Modifié de 16 à 26 pour descendre de 10 pixels
    left: 16,
    backgroundColor: "white",
    borderRadius: 8,
    padding: 10,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  hamburgerIcon: {
    width: 20,
    height: 15,
    justifyContent: "space-between",
  },
  hamburgerLine: {
    width: "100%",
    height: 2,
    backgroundColor: "#0a7ea4",
    borderRadius: 1,
  },
  optionsButtonText: {
    fontWeight: "bold",
    color: "#0a7ea4",
  },
  zoomButtons: {
    position: "absolute",
    right: 16,
    bottom: 16,
    backgroundColor: "white",
    borderRadius: 8,
    padding: 8,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  instructionContainer: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
  },
  noRouteContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  noRouteText: {
    textAlign: "center",
    color: "#555",
  },
  loader: { flex: 1, justifyContent: "center", alignItems: "center" },
  row: { flexDirection: "row", alignItems: "center", marginVertical: 8 },
  label: { fontWeight: "bold", marginTop: 8 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 4,
    padding: 8,
    marginTop: 4,
    marginBottom: 12,
  },
  instruction: {
    padding: 12,
    borderWidth: 1,
    borderColor: "#0d6efd",
    borderRadius: 6,
    backgroundColor: "#e7f1ff",
  },
  instructionTitle: { fontWeight: "bold", marginBottom: 4 },
  instructionText: { fontSize: 16 },
  instructionSub: { fontSize: 12, color: "#555" },
  error: { color: "crimson", marginTop: 8 },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    width: width * 0.9,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: "#6c757d",
    padding: 10,
    borderRadius: 5,
    flex: 1,
    marginRight: 10,
    alignItems: "center",
  },
  calculateButton: {
    backgroundColor: "#0a7ea4",
    padding: 10,
    borderRadius: 5,
    flex: 1,
    marginLeft: 10,
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
  },
  recenterButton: {
    position: "absolute",
    top: 40,
    right: 16,
    backgroundColor: "white",
    borderRadius: 8,
    padding: 10,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  recenterIcon: {
    width: 20,
    height: 20,
    position: "relative",
  },
  recenterCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#0a7ea4",
    position: "absolute",
    top: 2,
    left: 2,
  },
  recenterCross: {
    width: 10,
    height: 10,
    position: "absolute",
    top: 5,
    left: 5,
    borderColor: "#0a7ea4",
    borderTopWidth: 2,
    borderLeftWidth: 2,
  },
  estimatedTime: {
    fontSize: 14,
    color: "#555",
    marginBottom: 8,
    fontWeight: "bold",
    textAlign: "left",
  },
});
