services:
  postgres:
    image: postgres:13
    container_name: trafine-postgres
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: trafine-backend
    env_file:
      - ../backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: trafine-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  postgres_data:
