version: '3'
services:
  osrm:
    build:
      context: ../osrm
      dockerfile: Dockerfile
    container_name: trafine-osrm
    ports:
      - "5000:5000"
    volumes:
      - osrm_data:/data
    networks:
      - trafine-net

  postgres:
    image: postgis/postgis:13-3.1-alpine
    container_name: trafine-postgres
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trafine-net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: trafine-backend
    env_file:
      - ../backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - osrm
    networks:
      - trafine-net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: trafine-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - trafine-net

  mobile:
    build:
      context: ../mobile
    container_name: trafine-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    networks:
      - trafine-net

volumes:
  osrm_data:
  postgres_data:

networks:
  trafine-net:
    driver: bridge
